== Welcome to the Red Hat CTF

=== Abstract:

Join us for the inaugural Red Hat One Capture The Flag event, where you will compete in teams of 10 against your colleagues. 

This challenge will require you to collaborate on complex tasks designed to test your troubleshooting skills with Ansible, OpenShift, and Red Hat Enterprise Linux. 

The tasks are based on material from the RHCSA, RHCE, DO180/DO280 (OpenShift) course material. 

These skills will not only test your technical skills, but also your teamwork and leadership skills. 

Not only will you be competing against the other teams in the room, but you'll be competing against everyone who participates at Red Hat One. 

Come take a crack at your chance at a grand prize.

=== Getting Started

* Join us live at Red Hat One
* Walk into assigned CTF room
* Watch the rotating Slide with instructions
* Identify your Skill Set (Platform, Ansible, Openship, Leadership) 
* Grab Stickers / Wrist Band With Skill 
* Join Team / Find table 
* Go To https://red.ht/rh1ctf[CTF Login Page] on your laptop or mobile device
* Go through first 5 quests on how to use CTFd
* Bug reporting page
* Get Started

=== Categories of Questions

https://github.com/RedHatQuickCourses/rh1-lab30-capture-the-flag/blob/main/content/modules/ROOT/pages/module-01.adoc[Red Hat Enterprise Linux]

https://github.com/RedHatQuickCourses/rh1-lab30-capture-the-flag/blob/main/content/modules/ROOT/pages/module-02.adoc[Ansible Automation Platform]

https://github.com/RedHatQuickCourses/rh1-lab30-capture-the-flag/blob/main/content/modules/ROOT/pages/module-03.adoc[OpenShift]

=== Speaker Information:

* Matt Sweitkert

* Morgan Peterman

* Mark Knittel

* Joshua Loscar 


=== Presentation Slides:
* 
