== Welcome to the Red Hat CTF

=== Abstract:

Join us for the inaugural Red Hat One Capture The Flag event, where you will compete in teams of 10 against your colleagues. 

This challenge will require you to collaborate on complex tasks designed to test your troubleshooting skills with Ansible, OpenShift, and Red Hat Enterprise Linux. 

The tasks are based on material from the RHCSA, RHCE, DO180/DO280 (OpenShift) course material. 

These skills will not only test your technical skills, but also your teamwork and leadership skills. 

Not only will you be competing against the other teams in the room, but you'll be competing against everyone who participates at Red Hat One. 

Come take a crack at your chance at a grand prize.


=== Getting Started

* Join us live at Red Hat One
* Follow the Documentation to do this on your own linux machine inside of a VM.

=== How to Follow along with the lab.

* https://github.com/rhpds/summit_2024_RHELevant_Security_Practices_Lab_LB1964/blob/main/content/modules/ROOT/pages/index.adoc[Lab Landing Page]
* https://github.com/rhpds/summit_2024_RHELevant_Security_Practices_Lab_LB1964/blob/main/content/modules/ROOT/pages/lab_1_rhpds_lab_setup.adoc[RHPDS Lab Setup]

=== Speaker Information:

* Matt Sweitkert

* Morgan Peterman

* Mark Knittel

* Joshua Loscar 


=== Presentation Slides:
* 
