= {lab_name}

Join us for the inaugural Red Hat One Capture The Flag event, where you will compete in teams of 10 against your colleagues.

This challenge will require you to collaborate on complex tasks designed to test your troubleshooting skills with Ansible, OpenShift, and Red Hat Enterprise Linux.

The tasks are based on material from the RHCSA, RHCE, DO180/DO280 (OpenShift) course material.

These skills will not only test your technical skills, but also your teamwork and leadership skills.

Not only will you be competing against the other teams in the room, but you’ll be competing against everyone who participates at Red Hat One.

Come take a crack at your chance at a grand prize.

== What do you need to partisipate 

* a laptop
* a spot at a table
* a teamname

== Tasks and Roles

* We will cover topics for RHEL, Ansible & Openshift

** https://github.com/RedHatQuickCourses/rh1-lab30-capture-the-flag/blob/main/content/modules/ROOT/pages/module-01.adoc[RHEL Tasks]

** https://github.com/RedHatQuickCourses/rh1-lab30-capture-the-flag/blob/main/content/modules/ROOT/pages/module-02.adoc[Ansible Tasks]

** https://github.com/RedHatQuickCourses/rh1-lab30-capture-the-flag/blob/main/content/modules/ROOT/pages/module-03.adoc[Openshift Tasks]


=== Lab Access

You will use this link to access the CTF[placeholder]

